# Site settings
title: Michael Lin
email: michaellam.lzc@gmail.com
url: http://www.michaellin.me
description: "This is Michael's home page. I'm trying to be a awesome programer."
skills: "Software Developer - Web Developer - Linux"
meta_author: Lin Michael

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: exiasr

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Michael Lin
  #location: Location
  social: Around the Web
  credits: Credits
  license: License

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://ca.linkedin.com/in/michaellinlzc
  - title: facebook
    url: https://www.facebook.com/michael.lam.1650332
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/ExiaSR

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Powered by Jekyll'

# License content
license:

# Build settings
markdown: kramdown
permalink: pretty
