# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
    - jekyll-gist
    - jekyll-paginate
    - redcarpet

# Permalinks
permalink:        pretty
# relative_permalinks: true
paginate_path: "/blog/page:num/"

# Setup
homepage_title:   Michael Lin | Blog
title:            Michael Lin
tagline:          'Blog'
description:      Learning to be an awesome programmer
url:              https://michaellin.me
baseurl:          /

# Extra
paginate:         5

# Comments
disqus_username:    exiasr

# social network
social:
    - title: key
      url: https://keybase.io/exiasr
    - title: github
      url: https://github.com/ExiaSR
    - title: linkedin
      url: https://ca.linkedin.com/in/michaellinlzc
    - title: envelope
      url: mailto:michaellin@ualberta.ca

# Reference(Friends)
friends:
    - title: Luojia
      url: https://luojia.me
      description: 可爱的男孩子
      favicon: https://luojia.me/favicon.ico
