# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
    - jekyll-gist
    - jekyll-paginate
    - redcarpet

# Permalinks
permalink:        pretty
# relative_permalinks: true
paginate_path: "/blog/page:num/"

# Setup
title:            Michael Lin
tagline:          'My personal page'
description:      'Software Developer'
url:              http://michaellin.me
baseurl:          /

author:
  name:           'Michael Lin'
  url:            http://michaellin.me

paginate:         5

github:
  repo:           https://github.com/ExiaSR
