# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
    - jekyll-gist
    - jekyll-paginate
    - redcarpet
    - jekyll-sitemap
    - jekyll-admin
# Permalinks
permalink:        pretty
# relative_permalinks: true
paginate_path: "/blog/page:num/"

# Setup
homepage_title:   Michael Lin | Blog
title:            Michael Lin
tagline:          'Blog'
description:      Learning to be an awesome programmer
url:              https://michaellin.me
baseurl:          /

# Extra
paginate:         5

# Comments
disqus_username:    exiasr

# social network
social:
    - title: key
      url: https://keybase.io/exiasr
    - title: github
      url: https://github.com/ExiaSR
    - title: linkedin
      url: https://ca.linkedin.com/in/michaellinlzc
    - title: envelope
      url: mailto:michaellin@ualberta.ca

# Reference(Friends)
friends:
    - title: Luojia
      url: https://luojia.me
      description: 可爱的男孩子
      favicon: https://luojia.me/favicon.ico
    - title: BlackGlory
      url: https://www.blackglory.me
      description: 写代码的游戏玩家
      favicon: https://www.blackglory.me/assets/favicon.ico
    - title: DigitalOcean
      url: https://m.do.co/c/faff46d8cc4b
      description: Get $10 by using my link to signup
      favicon: https://www.digitalocean.com/favicon.ico
    - title: Vultr
      url: http://www.vultr.com/?ref=6900414
      description: Get $10 by using my link to signup
      favicon: https://www.vultr.com/favicon.ico
    - title: Vnet.link
      url: https://vnet.one/rc31
      description: 加速访问国内网站
      favicon: https://vnet.link/favicon.ico
